### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by Gorgoras** [scottmelhop/PowerBI-API-Python#20]
Hey guys, I'm currently interested in developing a Power Bi Api wrapper for Python, there are a lot but not with all functionalities and most of them are kind of forgotten. 

This one seems to include more than others, and seeing the last commit 3 months ago seems promising also, compared to others.

Should I try to improve this one or just continue on my own (maybe forking it?)?

**Comment by magnusnyborgmoan** [comment]
Hi @Gorgoras! 

Sorry for not getting back to you sooner. Feel free to contribute here if you want to.

Currently it is not actively being developed.

/Magnus

**Comment by Gorgoras** [comment]
Great! I'll try to find some time to contribute :)
